## promise.all里面有多个promise如果其中一个出错，那我怎么才能拿到剩余结果


### 实现代码

```js
var p1 = new Promise((resolve, reject) => {
    resolve('p1');
});
var p2 = new Promise((resolve, reject) => {
    resolve('p2');
});
var p3 = new Promise((resolve, reject) => {
    reject('p3');
});
Promise.all([p1, p2, p3].map(p => p.catch(e => '出错后返回的值' )))
.then(values => {
    console.log(values);
}).catch(err => {
    console.log(err);
});
```